kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: paper-service-pvc
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi